train:
  way: 5
  shot: 5
  num_session: 5
  num_base: 80
  num_novel: 20
  num_all: 100
  start_session: 1
  test_times: 50
  seq_sample: false
  tmp_train: true
  feat_dim: 512
  save_dir: /data/lqq/baseline/save/
  seed: 3420
  n_ways: 5 #meta-training
  n_open_ways: 5
  n_shots: 5
  n_queries: 15
  n_test_runs: 300
  n_train_runs: 300
  train_classes: 80
  epochs:
    epochs_std: 30 #30 # epochs for standard train
    epochs_meta: 1
    epochs_stdu_base: 1 # epochs for incremental train
    epochs_new: 5 # epochs for incremental session
  lr:
    lr_std: !!float 0.005 # lr for standard train
    lr_stdu_base: !!float 0.0002 # lr for encoder in increment train stage
    lrg: !!float 0.1  # lr for graph attention
    lr_new: !!float 0.1 # lr for incremental session
    lr_decay_rate: !!float 0.1
    lr_decay_epochs: "20 50 100"
  scheduler: 
    schedule: Step # ['Step', 'Milestone']
    milestones: [40, 80]
    step: 40
    gamma: !!float 0.5
  optimizer:
    decay: !!float 0.0005
    momentum: !!float 0.9
  network:
    temperature: 1
    base_mode: ft_cos  # ['ft_dot', 'ft_cos']
    new_mode: ft_cos  # ['ft_dot', 'ft_cos', 'avg_cos'] ft_dot means using linear classifier, ft_cos means using cosine classifier, avg_cos means using average data embedding and cosine classifier
  strategy:
    data_init: true
    set_no_val: false
    seq_sample: false
  episode:
    train_episode: 50
    episode_way: 5
    episode_shot: 5
    episode_query: 15
    low_way: 5
    low_shot: 5
  dataloader:
    num_workers: 8
    train_batch_size: 128
    test_batch_size: 100
  stdu:
    num_tmpb: 55
    num_tmpi: 25
    num_tmps: 14
    num_incre: 5
    pqa: false
    ap:
      use_ap: true
      ap_type: outer
      ap_on_test: false
    anchor:
      use_anchor: false
      anchor_type: base_anchor
    proto:
      weighted: false
      type: mmt  # ['mmt', 'res']
  extractor:
    sample_rate: 16000
    window_size: 400
    hop_size: 160
    mel_bins: 128
    fmin: 0
    fmax: 8000
    window: hann



